export const MAX_CONCURRENT_VIDEO_JOBS = 3;
export const CHAT_TAIL_LIMIT_WHEN_SPLIT = 3;

export const state = {
  stage: "awaitMain",
  images: [],
  productAnchors: {},
  productName: "",
  mainBusiness: "",
  sellingPoints: "",
  targetUser: "",
  salesRegion: "",
  brandInfo: "",
  reviewPositivePoints: [],
  reviewNegativePoints: [],
  productImageUrls: [],
  template: "clean",
  duration: "16",
  aspectRatio: "16:9",
  needModel: true,
  summaryShown: false,
  regionBatchIdx: 0,
  targetBatchIdx: 0,
  brandBatchIdx: 0,
  generating: false,
  activeVideoJobs: 0,
  taskSeq: 0,
  taskMap: {},
  enhancing: false,
  firstFrame: null,
  lastFrame: null,
  frameMode: false,
  videoEditorOpen: false,
  scriptEditorOpen: false,
  lastPrompt: "",
  lastStoryboard: "",
  lastVideoUrl: "",
  primarySubmitLocked: false,
  canUseEditors: false,
  workflowHydrating: false,
  workflowHydrated: false,
  skipImageConfirmed: false,
  entryFocusMode: false,
  lastModelAdviceKey: "",
  activeVideoCardId: "",
  videoUrlHistory: [],    // max-10 undo stack — push before each export
  pendingEditExport: null, // stored async fn for preview-confirm flow
  videoEdit: {
    maskText: "",
    maskStyle: "elegant",
    maskFont: "sans",
    maskColor: "#ffffff",
    x: 10,
    y: 0,
    w: 80,
    h: 12,
    opacity: 90,
    rotation: 0,
    speed: "1.0",
    temp: 12,
    tint: 5,
    sat: 8,
    vibrance: 10,
    bgmExtract: true,
    bgmMood: "elegant",
    bgmVolume: 70,
    bgmReplaceMode: "auto",
    localBgmUrl: "",
    localBgmName: "",
    localBgmDataUrl: "",
    activeModule: "mask",
    _renderHash: "",
    timeline: {
      playhead: 0,
      selectedTrack: "mask",
      trackState: {
        mask: { visible: true, locked: false },
        color: { visible: true, locked: false },
        bgm: { visible: true, locked: false },
        motion: { visible: true, locked: false },
      },
      keyframes: {
        mask: [0, 2.2, 5.4],
        color: [1.2, 4.8],
        bgm: [0, 6.4],
        motion: [3.1],
      },
    },
  },
};

export const smartOptionCache = {
  signature: "",
  targetPool: [],
  brandPool: [],
  loading: null,
};
